- designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/Badge.kt
> Feature/Design System Badge

- designsystem/src/main/java/com/apeun/gidaechi/designsystem/animation/ButtonClick.kt
- designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/Category.kt
- #26 
- Remove BoundClick Background
- Add BoundClick Output Change ButtonState
> Feature/Design System Category

- designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/chat/ChatList.kt
> Feature/Design System Chat List

- designsystem/src/main/java/com/apeun/gidaechi/designsystem/animation/AlphaIndication.kt
- designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/MemberList.kt
- designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/chat/ChatItem.kt
- designsystem/src/main/res/drawable/ic_add_ring_line.xml
> Feature/Design System Member List

- designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/Divider.kt
> Feature/Design System Divider

- .github/workflows/ci.yml
> CI/Create CD Flow

- feature-onboarding/join/src/main/java/com/apeun/gidaechi/EmailSignUp.kt
- feature-onboarding/join/src/main/java/com/apeun/gidaechi/EmailVerification.kt
- feature-onboarding/join/src/main/java/com/apeun/gidaechi/JoinSuccess.kt
- feature-onboarding/join/src/main/java/com/apeun/gidaechi/OAuthSignUp.kt
- feature-onboarding/join/src/main/java/com/apeun/gidaechi/SchoolCode.kt
- feature-onboarding/join/src/main/java/com/apeun/gidaechi/SelectingJob.kt
- feature-onboarding/join/src/main/java/com/apeun/gidaechi/WaitingJoin.kt
- feature-onboarding/join/src/main/java/com/apeun/gidaechi/navigation/WaitingJoinNavigation.kt
- feature-onboarding/login/src/main/java/com/apeun/gidaechi/login/EmailSignInScreen.kt
- feature-onboarding/onabording/src/main/java/com/apeun/gidaechi/OnboardingScreen.kt
> Fix/Develop Merge Issues

- designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/RoundedCircleImage.kt
> Feature/Add Image Border

- app/src/main/java/com/apeun/gidaechi/seugi/MainActivity.kt
- feature-onboarding/login/src/main/java/com/apeun/gidaechi/login/EmailSignInScreen.kt
- feature-onboarding/login/src/main/java/com/apeun/gidaechi/login/navigation/EmailSignInNavigation.kt
- feature-onboarding/onabording/src/main/java/com/apeun/gidaechi/OnboardingScreen.kt
- 로그인에서 메인으로 가는 네비게이션으로 변경
- close #132
> Feature/Create Login To Mian

- data/core/src/main/java/com/apeun/gidaechi/data/core/mapper/ChatRoomMapper.kt
- data/core/src/main/java/com/apeun/gidaechi/data/core/model/ChatRoomModel.kt
- data/message/src/main/java/com/apeun/gidaechi/message/mapper/MessageMapper.kt
- data/message/src/main/java/com/apeun/gidaechi/message/mapper/MessageRoomMapper.kt
- data/message/src/main/java/com/apeun/gidaechi/message/mapper/MessageSubMapper.kt
- data/message/src/main/java/com/apeun/gidaechi/message/model/message/MessageEmojiModel.kt
- data/message/src/main/java/com/apeun/gidaechi/message/model/message/MessageLoadModel.kt
- data/message/src/main/java/com/apeun/gidaechi/message/model/message/MessageMessageDeleteModel.kt
- data/message/src/main/java/com/apeun/gidaechi/message/model/message/MessageMessageModel.kt
- data/message/src/main/java/com/apeun/gidaechi/message/model/room/MessageRoomModel.kt
- data/message/src/main/java/com/apeun/gidaechi/message/model/sub/MessageSubModel.kt
- Data Layer에 존재하는 List Type을 ImmutableList Type으로 변환하였습니다.
- close #120
> Refactor/Data Layer Model

- feature-main/home/src/main/java/com/apeun/gidaechi/home/HomeScreen.kt
- 홈 화면에 아이콘의 색상이 잘못되어있던 점을 수정하였습니다.
- close #140
> Feature/Home Screen Calendar Color Edit

- designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/LoadingDotsIndicator.kt
- feature-main/home/src/main/java/com/apeun/gidaechi/home/HomeScreen.kt
- feature-main/home/src/main/java/com/apeun/gidaechi/home/HomeViewModel.kt
- feature-main/home/src/main/java/com/apeun/gidaechi/home/model/HomeUiState.kt
- 아이템이 존재하지 않을 경우 화면을 개발하였습니다.
- 로딩중인 경우 사용할 Indicator를 개발하였습니다.
- close #149
> Feature/Home Screen Not Found

- app/src/main/java/com/apeun/gidaechi/seugi/MainActivity.kt
- feature-main/main/src/main/java/com/apeun/gidaechi/main/MainScreen.kt
- feature-main/main/src/main/java/com/apeun/gidaechi/main/navigation/MainNavigation.kt
- feature-onboarding/join/src/main/java/com/apeun/gidaechi/EmailVerificationScreen.kt
- feature-onboarding/join/src/main/java/com/apeun/gidaechi/navigation/EmailVerificationNavigation.kt
- feature-onboarding/onabording/src/main/java/com/apeun/gidaechi/OnboardingScreen.kt
- 변경된 네비게이션 수정
> 메인에서 뒤로가기 로직이 맞는지 확인부탁들입니다.
- close #153
> Feature/Edit Navigation

- feature-main/home/src/main/java/com/apeun/gidaechi/home/HomeScreen.kt
- feature-main/home/src/main/java/com/apeun/gidaechi/home/HomeViewModel.kt
- feature-main/home/src/main/java/com/apeun/gidaechi/home/model/HomeUiState.kt
- 홈 화면에서 학교를 변경하는 기능을 만들었습니다.
- close #161
> Feature/Home School Change

- data/message/src/main/java/com/apeun/gidaechi/message/model/room/MessageRoomModel.kt
- feature-main/chat-seugi/src/main/java/com/apeun/gidaechi/chatseugi/ChatSeugiViewModel.kt
- feature-main/home/src/main/java/com/apeun/gidaechi/home/HomeViewModel.kt
- network/message/src/main/java/com/apeun/gidaechi/network/message/response/room/MessageRoomResponse.kt
- 더미의 잘못된 D-Day를 수정하였습니다.
- close #167
> Refactor/Edit School Schedule D-day

- data/token/build.gradle.kts
- network/core/build.gradle.kts
- network/core/src/main/java/com/apeun/gidaechi/network/core/di/NetworkModule.kt
- network/core/src/main/java/com/apeun/gidaechi/network/core/utiles/Extension.kt
> Feature/Create Interceptor

- feature-onboarding/join/build.gradle.kts
- feature-onboarding/join/src/main/java/com/seugi/join/EmailVerificationScreen.kt
- 이메일 인증 번호 요청에서 발생한 side effect 버그 수정
- close #172
> Fix/Side Effect

- data/profile/build.gradle.kts
- feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailScreen.kt
- feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailViewModel.kt
- feature-main/chat-datail/src/main/java/com/seugi/chatdatail/navigation/ChatDetailNavigation.kt
- feature-main/chat/src/main/java/com/seugi/chat/ChatScreen.kt
- feature-main/chat/src/main/java/com/seugi/chat/ChatViewModel.kt
- feature-main/chat/src/main/java/com/seugi/chat/navigation/ChatNavigation.kt
- feature-main/main/build.gradle.kts
- feature-main/main/src/main/java/com/seugi/main/MainScreen.kt
- feature-main/main/src/main/java/com/seugi/main/MainViewModel.kt
- feature-main/main/src/main/java/com/seugi/main/model/MainContract.kt
- feature-main/main/src/main/java/com/seugi/main/model/MainUiState.kt
- feature-main/profile/src/main/java/com/seugi/profile/ProfileScreen.kt
- feature-main/profile/src/main/java/com/seugi/profile/ProfileViewModel.kt
- feature-main/profile/src/main/java/com/seugi/profile/navigation/ProfileNavigation.kt
- feature-main/room/src/main/java/com/seugi/room/RoomScreen.kt
- feature-main/room/src/main/java/com/seugi/room/RoomViewModel.kt
- feature-main/room/src/main/java/com/seugi/room/navigation/RoomNavigation.kt
- network/token/src/main/java/com/seugi/network/token/datasource/TokenDatasourceImpl.kt
- MainScreen에서 워크스페이스 ID를 관리하도록 하였습니다.
- 채팅 로직에서 에러가 있는 부분을 수정하였습니다.
- close #188
> Feature/Main Manage Workspace

- designsystem-preview/src/main/java/com/apeun/gidaechi/designsystem/preview/feature/Dialog.kt
- designsystem/src/main/java/com/seugi/designsystem/component/Dialog.kt
- feature-main/home/src/main/java/com/seugi/home/HomeScreen.kt
- feature-main/home/src/main/java/com/seugi/home/HomeViewModel.kt
- feature-main/home/src/main/java/com/seugi/home/model/HomeUiState.kt
- 홈 화면에서 워크페이스로 이동하는 로직
- 처음 로컬에 워크페이스가 없을때 나오는 dialog 제작
- close #192
> Feature/Link Workspace To Home

- designsystem/src/main/java/com/seugi/designsystem/component/DatePicker.kt
- 기존 DatePicker Indicator 의 offset을 조절하는 로직에 이상이 발견되어 수정하였습니다.
- close #199
> Refactor/Date Picker Indicator Offset Logic

- data/workspace/build.gradle.kts
- data/workspace/src/main/java/com/seugi/data/workspace/WorkspaceRepository.kt
- data/workspace/src/main/java/com/seugi/data/workspace/mapper/WorkspaceMapper.kt
- data/workspace/src/main/java/com/seugi/data/workspace/repository/WorkspaceRepositoryImpl.kt
- feature-main/home/src/main/java/com/seugi/home/HomeScreen.kt
- feature-main/home/src/main/java/com/seugi/home/HomeViewModel.kt
- feature-main/main/src/main/java/com/seugi/main/MainScreen.kt
- feature-main/workspace-detail/build.gradle.kts
- feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/WorkspaceDetailScreen.kt
- feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/model/WorkspaceDetailUiState.kt
- feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacemember/WorkspaceMemberScreen.kt
- feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacemember/WorkspaceMemberViewModel.kt
- feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacemember/model/WorkspaceMemberUiState.kt
- feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/navigation/WorkspaceDetailNavigation.kt
- feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/navigation/WorkspaceMemberNavigation.kt
- local/room/src/main/java/com/seugi/local/room/dao/WorkspaceDao.kt
- network/core/src/main/java/com/seugi/network/core/SeugiUrl.kt
- 워크페이스 멤버 조회
> workspace data 를 참조하는데 왜 core의 값을 참조 못하는 건가요
- close #198
> Feature/Create Workspace Member

- feature-onboarding/join/src/main/java/com/seugi/join/feature/EmailSignUpScreen.kt
- feature-onboarding/join/src/main/java/com/seugi/join/feature/OAuthSignUpScreen.kt
- feature-onboarding/login/src/main/java/com/seugi/login/EmailSignInScreen.kt
- 에러 문자 페딩을 변경했습니다
- close #205
> refactor: Error Text Padding

- feature-main/workspace/src/main/java/com/seugi/workspace/feature/joinsuccess/JoinSuccessScreen.kt
- feature-main/workspace/src/main/java/com/seugi/workspace/navigation/JoinSuccessNavigation.kt
-  이미지가 없을때 생기는 네비게이션 버그 수정
- close #206
> Fix/Null Image Bug

- feature-onboarding/start/src/main/java/com/seugi/start/StartScreen.kt
- 시작 화면에서 나오는 애니메이션 제작
- close #218
> Feature/Create Start Animation

- app/src/main/java/com/seugi/MainActivity.kt
- Launch Screen 나오는 시간 2초로 설정
- close #221
> Feature/Edit Launch Screen Time

- feature-main/home/src/main/java/com/seugi/home/HomeScreen.kt
- feature-main/home/src/main/java/com/seugi/home/HomeViewModel.kt
- feature-main/home/src/main/java/com/seugi/home/navigation/HomeNavigation.kt
- feature-main/main/src/main/java/com/seugi/main/MainScreen.kt
- feature-main/main/src/main/java/com/seugi/main/MainViewModel.kt
- 워크페이스 불러오는 과정에서 꼬인 순서를 수정했습니다.
- close #228
> Fix/Load Workspace Id Bug

- feature-main/main/src/main/java/com/seugi/main/MainScreen.kt
- feature-main/main/src/main/java/com/seugi/main/MainViewModel.kt
- feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/WorkspaceDetailScreen.kt
- feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/WorkspaceDetailViewModel.kt
- feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/navigation/WorkspaceDetailNavigation.kt
- Create Load Local Id
- close #231
> Feature/Create Load Local Id

- feature-main/main/src/main/java/com/seugi/main/MainScreen.kt
- feature-main/main/src/main/java/com/seugi/main/MainViewModel.kt
- feature-main/room-create/src/main/java/com/seugi/roomcreate/RoomCreateScreen.kt
- feature-main/room-create/src/main/java/com/seugi/roomcreate/RoomCreateViewModel.kt
- feature-main/room-create/src/main/java/com/seugi/roomcreate/navigation/RoomCreateNavigation.kt
- feature-main/room-create/src/main/java/com/seugi/roomcreate/screen/FirstScreen.kt
- feature-main/room/src/main/java/com/seugi/room/RoomScreen.kt
- feature-main/room/src/main/java/com/seugi/room/navigation/RoomNavigation.kt
- Create Room Member Filter
- close #233
> Feature/Create Room Member Filter

- data/message/src/main/java/com/seugi/data/message/mapper/MessageStompMapper.kt
- data/message/src/main/java/com/seugi/data/message/model/stomp/MessageStompLifecycleModel.kt
- feature-main/chat-datail/build.gradle.kts
- feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailScreen.kt
- feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailViewModel.kt
- network/core/src/main/java/com/seugi/network/core/SeugiUrl.kt
- network/core/src/main/java/com/seugi/network/core/di/NetworkModule.kt
- network/group-chat/src/main/java/com/seugi/network/groupchat/datasource/GroupChatDataSourceImpl.kt
- network/message/src/main/java/com/seugi/network/message/datasource/MessageDataSourceImpl.kt
- network/message/src/main/java/com/seugi/network/message/request/MessageRequest.kt
- network/message/src/main/java/com/seugi/network/message/response/stomp/MessageStompLifecycleResponse.kt
- network/personal-chat/src/main/java/com/apeun/gidaechi/data/personalchat/datasource/PersonalChatDataSourceImpl.kt
- stomp-client/src/main/java/com/seugi/stompclient/StompClient.java
- stomp-client/src/main/java/com/seugi/stompclient/dto/LifecycleEvent.java
- stomp-client/src/main/java/com/seugi/stompclient/provider/AbstractConnectionProvider.java
- stomp-client/src/main/java/com/seugi/stompclient/provider/OkHttpConnectionProvider.java
- stomp-client/src/main/java/com/seugi/stompclient/provider/WebSocketsConnectionProvider.java
- 네트워크 전환시 소켓이 끊기거나, 끊겼을떄 다시 재연결되지 않는 등의 버그를 수정하였습니다.
- close #227
> Fix/Chat Detail Bug

- feature-main/main/src/main/java/com/seugi/main/MainScreen.kt
- feature-main/main/src/main/java/com/seugi/main/MainViewModel.kt
- feature-main/main/src/main/java/com/seugi/main/model/MainUiState.kt
- feature-main/profile/src/main/java/com/seugi/profile/ProfileScreen.kt
- feature-main/profile/src/main/java/com/seugi/profile/ProfileViewModel.kt
- feature-main/profile/src/main/java/com/seugi/profile/navigation/ProfileNavigation.kt
- 메인에서 가져온 프로필을 프로필 화면에 보내기
- close #239
> Feature/Move Profile Data

- feature-main/home/src/main/java/com/seugi/home/HomeScreen.kt
- feature-main/home/src/main/java/com/seugi/home/HomeViewModel.kt
- feature-main/home/src/main/java/com/seugi/home/card/CatSeugiCard.kt
- feature-main/home/src/main/java/com/seugi/home/card/MealCard.kt
- feature-main/home/src/main/java/com/seugi/home/card/ScheduleCard.kt
- feature-main/home/src/main/java/com/seugi/home/card/SchoolCard.kt
- feature-main/home/src/main/java/com/seugi/home/card/TimeScheduleCard.kt
- feature-main/home/src/main/java/com/seugi/home/model/HomeUiState.kt
- 기존 홈 화면의 코드가 너무 복잡하여 컴포넌트화 시켜 가독성을 개선하였습니다.
- 급식 카드에서 시간대에 따라 보여주는 페이지를 다르게 하였습니다.
- 서버에서 구현되지 않는 기능들은 Not Found로 보이게 하였습니다.
- close #243
> Refactor/Home Screen

- feature-main/chat/src/main/java/com/seugi/chat/ChatScreen.kt
- feature-main/room-create/src/main/java/com/seugi/roomcreate/screen/FirstScreen.kt
- feature-main/room-create/src/main/java/com/seugi/roomcreate/screen/SecondScreen.kt
- feature-main/room/src/main/java/com/seugi/room/RoomScreen.kt
- feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/WorkspaceDetailScreen.kt
- feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacemember/WorkspaceMemberScreen.kt
- 배경색이 적용되지 않은 이슈들을 해결하였습니다.
- close #250
> Feature/Set Lazy Column Background

- feature-main/main/src/main/java/com/seugi/main/MainScreen.kt
- feature-main/workspace-detail/build.gradle.kts
- feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacemember/WorkspaceMemberScreen.kt
- feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacemember/WorkspaceMemberViewModel.kt
- feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacemember/model/WorkspaceMemberSideEffect.kt
- feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/navigation/WorkspaceMemberNavigation.kt
- ui/build.gradle.kts
- ui/src/main/java/com/seugi/ui/component/OtherProfileBottomSheet.kt
- Other Profile Bottom Sheet 컴포넌트를 만들었습니다.
- Workspace Member 화면에서 멤버를 누를 경우 Bottom Sheet 을 띄워 채팅창으로 네비게이션 하도록 하였습니다.
- close #258
> Feature/Other Profile Bottom Sheet

- designsystem/src/main/java/com/seugi/designsystem/component/MemberList.kt
- feature-main/main/src/main/java/com/seugi/main/MainScreen.kt
- feature-main/workspace-detail/build.gradle.kts
- feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacemember/WorkspaceMemberScreen.kt
- feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacemember/WorkspaceMemberViewModel.kt
- feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacemember/model/WorkspaceMemberSideEffect.kt
- feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/navigation/WorkspaceMemberNavigation.kt
- ui/build.gradle.kts
- ui/src/main/java/com/seugi/ui/component/OtherProfileBottomSheet.kt
- 워크페이스 멤버들을 권한에 따라 분류하였습니다.
- 만약 권한이 어드민이면 왕관을 추가하였습니다.
- close #204
> Feature/Create Member Filter

- feature-main/home/src/main/java/com/seugi/home/HomeViewModel.kt
- feature-main/main/src/main/java/com/seugi/main/MainViewModel.kt
- feature-main/notification/src/main/java/com/seugi/notification/NotificationScreen.kt
- feature-main/profile/src/main/java/com/seugi/profile/ProfileScreen.kt
- feature-main/room/src/main/java/com/seugi/room/RoomScreen.kt
- feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/WorkspaceDetailViewModel.kt
- 워크페이스 아이디를 기준으로 하는 LaunchedEffect를 만듬
- 메인 뷰 모델 init로직 변경
> 워크페이스를 사용하는 스크린은 전부 전용하긴했는데 빠진 부분은 없는지 확인 부탁들입니다.
- close #276
> Refactor/Main ViewModel Logic

- data/token/src/main/java/com/seugi/data/token/repository/TokenRepositoryImpl.kt
- data/workspace/src/main/java/com/seugi/data/workspace/WorkspaceRepository.kt
- data/workspace/src/main/java/com/seugi/data/workspace/mapper/WorkspaceMapper.kt
- data/workspace/src/main/java/com/seugi/data/workspace/repository/WorkspaceRepositoryImpl.kt
- feature-main/home/src/main/java/com/seugi/home/HomeScreen.kt
- feature-main/home/src/main/java/com/seugi/home/HomeViewModel.kt
- feature-main/home/src/main/java/com/seugi/home/navigation/HomeNavigation.kt
- feature-main/main/src/main/java/com/seugi/main/MainScreen.kt
- feature-main/main/src/main/java/com/seugi/main/MainViewModel.kt
- feature-main/main/src/main/java/com/seugi/main/model/MainUiState.kt
- feature-main/meal-widget/src/main/java/com/seugi/meal/widget/MealWidget.kt
- feature-main/profile/src/main/java/com/seugi/profile/ProfileScreen.kt
- feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/WorkspaceDetailScreen.kt
- feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/WorkspaceDetailViewModel.kt
- feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/model/WorkspaceDetailUiState.kt
- feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/navigation/WorkspaceDetailNavigation.kt
- local/room/build.gradle.kts
- local/room/src/main/java/com/seugi/local/room/SeugiDatabase.kt
- local/room/src/main/java/com/seugi/local/room/dao/WorkspaceDao.kt
- local/room/src/main/java/com/seugi/local/room/di/SeugiDatabaseModule.kt
- local/room/src/main/java/com/seugi/local/room/model/WorkspaceEntity.kt
- local/room/src/main/java/com/seugi/local/room/util/LongListTypeConverter.kt
- network/core/src/main/java/com/seugi/network/core/SeugiUrl.kt
- network/core/src/main/java/com/seugi/network/core/di/NetworkModule.kt
- network/sign-in/src/main/java/com/seugi/network/datasource/MemberDatasourceImpl.kt
- network/token/build.gradle.kts
- network/token/src/main/java/com/seugi/network/token/TokenDatasource.kt
- network/token/src/main/java/com/seugi/network/token/datasource/TokenDatasourceImpl.kt
- 프로필 기능에서 지속적으로 상태를 초기화 하는 버그를 수정하였습니다.
- Home에서 워크스페이스의 상태를 들고있던 것을, Main에서 상태를 들고있도록 변경하였습니다.
- close #281
> Feature/Profile Load Logic

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/timetable_widget_info.xml
- data/timetable/src/main/java/com/seugi/data/timetable/mapper/TimetableMapper.kt
- data/timetable/src/main/java/com/seugi/data/timetable/model/TimetableModel.kt
- feature-main/timetable-widget/build.gradle.kts
- feature-main/timetable-widget/src/main/java/com/seugi/timetable/widget/TimetableWidget.kt
- feature-main/timetable-widget/src/main/java/com/seugi/timetable/widget/component/TimetableListProvider.kt
- feature-main/timetable-widget/src/main/java/com/seugi/timetable/widget/di/TimetableWidgetEntryPoint.kt
- feature-main/timetable-widget/src/main/java/com/seugi/timetable/widget/di/WidgetModule.kt
- feature-main/timetable-widget/src/main/res/drawable/shape100_primary050.xml
- feature-main/timetable-widget/src/main/res/drawable/shape18_white.xml
- feature-main/timetable-widget/src/main/res/drawable/shape22_neutral.xml
- feature-main/timetable-widget/src/main/res/layout/item_meal_menu.xml
- feature-main/timetable-widget/src/main/res/layout/widget_timetable_layout.xml
- feature-main/timetable-widget/src/main/res/values/strings.xml
- feature-main/timetable-widget/src/main/res/values/styles.xml
- gradle/libs.versions.toml
- network/core/src/main/java/com/seugi/network/core/di/NetworkModule.kt
- network/core/src/main/java/com/seugi/network/core/response/FakeLocalDateResponse.kt
- network/core/src/main/java/com/seugi/network/core/utiles/FakeLocalDateResponseTypeAdapter.kt
- network/timetable/build.gradle.kts
- network/timetable/src/androidTest/java/com/seugi/network/timetable/TimetableDataSourceTest.kt
- network/timetable/src/main/java/com/seugi/network/timetable/response/TimetableResponse.kt
- settings.gradle.kts
- 시간표 위젯을 만들었습니다.
- close #288
> Feature/Timetable Widget

- data/member/src/main/java/com/seugi/data/member/MemberRepository.kt
- data/member/src/main/java/com/seugi/data/member/repository/MemberRepositoryImpl.kt
- feature-main/home/src/main/java/com/seugi/home/HomeScreen.kt
- feature-main/main/src/main/java/com/seugi/main/MainScreen.kt
- feature-main/profile/src/main/java/com/seugi/profile/ProfileScreen.kt
- feature-main/room-create/src/main/java/com/seugi/roomcreate/screen/FirstScreen.kt
- feature-main/setting/build.gradle.kts
- feature-main/setting/src/main/java/com/seugi/setting/SettingScreen.kt
- feature-main/setting/src/main/java/com/seugi/setting/SettingViewModel.kt
- feature-main/setting/src/main/java/com/seugi/setting/model/SettingSideEffect.kt
- feature-main/setting/src/main/java/com/seugi/setting/navigate/SettingNavigate.kt
- feature-main/workspace-create/src/main/java/com/seugi/workspacecreate/WorkspaceCreateScreen.kt
- feature-main/workspace-create/src/main/java/com/seugi/workspacecreate/WorkspaceCreateViewModel.kt
- feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/WorkspaceDetailScreen.kt
- network/core/src/main/java/com/seugi/network/core/SeugiUrl.kt
- network/sign-in/src/main/java/com/seugi/network/MemberDatasource.kt
- network/sign-in/src/main/java/com/seugi/network/datasource/MemberDatasourceImpl.kt
- network/sign-in/src/main/java/com/seugi/network/request/EditRequest.kt
- 프로필 이미지 변경
- 워크페이스 만들때 이미지 있으면 버튼 안보이게
- 방 만들때 유저에 이미지 없으면 기본이미지
- 메인 pull refresh
> 파일을 이미지로 변환하는 기능이 중복되는 부분이 있어서 하나로 만들고 싶은데 방법이 있을까요?
- close #289
> Feature/Create Setting Feature

- data/core/src/main/java/com/seugi/data/core/mapper/UserMapper.kt
- data/message/src/main/java/com/seugi/data/message/MessageRepository.kt
- data/message/src/main/java/com/seugi/data/message/repository/MessageRepositoryImpl.kt
- feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailScreen.kt
- feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailViewModel.kt
- network/message/src/main/java/com/seugi/network/message/MessageDataSource.kt
- network/message/src/main/java/com/seugi/network/message/datasource/MessageDataSourceImpl.kt
- 채팅 페이징 기능을 개발하였습니다.
- close #291
> Feature/Chat Pagination

- data/core/src/main/java/com/seugi/data/core/model/ProfileModel.kt
- feature-main/room-create/src/main/java/com/seugi/roomcreate/RoomCreateViewModel.kt
- 프로필에서 간단히, 유저의 이름과 닉네임이 포함된 문자열을 가져올 수 있게 했습니다.
- close #294
> Refactor/User Name And Nick

- designsystem/src/main/java/com/seugi/designsystem/component/Button.kt
- feature-onboarding/start/src/main/java/com/seugi/start/StartScreen.kt
- 화면의 Height가 작은 경우, 버튼이 height가 짓눌리는 현상을 수정하였습니다.
- close #296
> Fix/Start Button Unresponsive

- designsystem/src/main/java/com/seugi/designsystem/animation/ButtonClick.kt
- designsystem/src/main/java/com/seugi/designsystem/component/Category.kt
- designsystem/src/main/java/com/seugi/designsystem/component/Dialog.kt
- designsystem/src/main/java/com/seugi/designsystem/component/ListItem.kt
- feature-main/home/src/main/java/com/seugi/home/HomeScreen.kt
- feature-main/home/src/main/java/com/seugi/home/card/MealCard.kt
- feature-main/notification/src/main/java/com/seugi/notification/NotificationScreen.kt
- scale 애니메이션이 이 바로 적용되지 않았던 문제를 적용하였습니다.
- close #298
> Fix/Bounce Click Scale Error

- feature-main/chat/src/main/java/com/seugi/chat/ChatScreen.kt
- feature-main/chat/src/main/java/com/seugi/chat/navigation/ChatNavigation.kt
- feature-main/main/src/main/java/com/seugi/main/MainScreen.kt
- 개인 채팅방 목록에서 방을 만들 수 있는 아이콘을 추가하였습니다.
- close #300
> Feature/Add Navigation Personal Chat

- feature-main/chat/src/main/java/com/seugi/chat/ChatScreen.kt
- feature-main/room/src/main/java/com/seugi/room/RoomScreen.kt
- 서버의 이미지를 받아 화면에 띄우게 하였습니다.
- close #302
> Feature/Reflect Room Remote Image

- feature-main/notification/src/main/java/com/seugi/notification/NotificationScreen.kt
- feature-main/notification/src/main/java/com/seugi/notification/NotificationViewModel.kt
- 공지 게시글 이모지 간 vertical padding을 추가했습니다.
- close #305
> Feature/Add Notification Emoji Spacing

- feature-main/home/src/main/java/com/seugi/home/HomeScreen.kt
- feature-main/home/src/main/java/com/seugi/home/HomeViewModel.kt
- feature-main/home/src/main/java/com/seugi/home/model/HomeUiState.kt
- feature-main/main/src/main/java/com/seugi/main/MainScreen.kt
- feature-main/main/src/main/java/com/seugi/main/MainViewModel.kt
- 처음 들어와서 워크페이스를 가입하고 내가 속한 워크페이스를 계속 불러와 소속되었다면 dialog를 내리는 기능을 개발
- close #309
> Feature/Create Re Load Workspace

- data/meal/src/main/java/com/seugi/data/meal/mapper/MealMapper.kt
- data/meal/src/main/java/com/seugi/data/meal/repository/MealRepositoryImpl.kt
- data/schedule/src/main/java/com/seugi/data/schedule/mapper/ScheduleMapper.kt
- data/timetable/src/main/java/com/seugi/data/timetable/mapper/TimetableMapper.kt
- network/core/src/main/java/com/seugi/network/core/di/NetworkModule.kt
- network/core/src/main/java/com/seugi/network/core/utiles/KotlinLocalDateTypeAdapter.kt
- network/meal/src/main/java/com/seugi/network/meal/MealDataSource.kt
- network/meal/src/main/java/com/seugi/network/meal/datasource/MealDataSourceImpl.kt
- network/meal/src/main/java/com/seugi/network/meal/response/MealResponse.kt
- network/schedule/src/main/java/com/seugi/network/schedule/response/ScheduleResponse.kt
- network/timetable/src/main/java/com/seugi/network/timetable/response/TimetableResponse.kt
- 서버에서 Date를 받는 형식이 변경되어 대응했습니다.
- close #311
> Fix/Date ISO Format

- feature-main/notification/src/main/java/com/seugi/notification/NotificationScreen.kt
- gradle/libs.versions.toml
- 기존 UI와 너무 어색해 새로운 라이브러리로 변경하였습니다.
- close #316
> Feature/Change Emoji Bottom Sheet

- designsystem/src/main/java/com/seugi/designsystem/component/TopBar.kt
- designsystem/src/main/java/com/seugi/designsystem/component/chat/ChatItem.kt
- feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailScreen.kt
- feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailViewModel.kt
- 채팅에서 검색기능을 개발하였습니다
- 각 메세지마다 readCount가 표기되도록 하였습니다.
- close #169
> Feature/Chat Detail Search

- designsystem/src/main/java/com/seugi/designsystem/component/ShimmerEffect.kt
- feature-main/room-create/src/main/java/com/seugi/roomcreate/RoomCreateViewModel.kt
- feature-main/room-create/src/main/java/com/seugi/roomcreate/model/RoomCreateUiState.kt
- feature-main/room-create/src/main/java/com/seugi/roomcreate/screen/FirstScreen.kt
- feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacemember/WorkspaceMemberScreen.kt
- feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacemember/WorkspaceMemberViewModel.kt
- feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacemember/model/WorkspaceMemberUiState.kt
- ui/src/main/java/com/seugi/ui/component/SeugiMemberListLoading.kt
- 워크스페이스에서 멤버를 불러올 경우, shimmer를 추가하였습니다.
- close #319
> Feature/Member Loading Shimmer

- feature-main/profile/src/main/java/com/seugi/profile/ProfileScreen.kt
- feature-main/setting/src/main/java/com/seugi/setting/SettingScreen.kt
- feature-main/setting/src/main/java/com/seugi/setting/SettingViewModel.kt
- 유저이름 수정
- 유저 닉네임, 근무장소 수정기능
- Profile Card가 많아져서 LazyColumn추가
- close #324
> Feature/Edit Profile Feature

- data/core/src/main/java/com/seugi/data/core/model/TimetableModel.kt
- data/timetable/src/main/java/com/seugi/data/timetable/TimetableRepository.kt
- data/timetable/src/main/java/com/seugi/data/timetable/mapper/TimetableMapper.kt
- data/timetable/src/main/java/com/seugi/data/timetable/repository/TimetableRepositoryImpl.kt
- feature-main/home/src/main/java/com/seugi/home/HomeScreen.kt
- feature-main/home/src/main/java/com/seugi/home/navigation/HomeNavigation.kt
- feature-main/main/build.gradle.kts
- feature-main/main/src/main/java/com/seugi/main/MainScreen.kt
- feature-main/timetable/build.gradle.kts
- feature-main/timetable/src/main/java/com/seugi/timetable/TimetableScreen.kt
- feature-main/timetable/src/main/java/com/seugi/timetable/TimetableViewModel.kt
- feature-main/timetable/src/main/java/com/seugi/timetable/navigation/TimetableNavigation.kt
- network/core/src/main/java/com/seugi/network/core/SeugiUrl.kt
- network/timetable/src/main/java/com/seugi/network/timetable/TimetableDataSource.kt
- network/timetable/src/main/java/com/seugi/network/timetable/datasource/TimetableDataSourceImpl.kt
- settings.gradle.kts
- 시간표 상세 화면을 만들었습니다.
- close #335
> Feature/Timetable Screen

- common/src/main/java/com/seugi/common/utiles/Extension.kt
- data/group-chat/src/main/java/com/seugi/data/groupchat/GroupChatRepository.kt
- data/group-chat/src/main/java/com/seugi/data/groupchat/repository/GroupChatRepositoryImpl.kt
- feature-main/chat-datail/build.gradle.kts
- feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailScreen.kt
- feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailViewModel.kt
- feature-main/chat-datail/src/main/java/com/seugi/chatdatail/model/ChatDetailUiState.kt
- feature-main/chat-datail/src/main/java/com/seugi/chatdatail/screen/ChatDetailChatScreen.kt
- feature-main/chat-datail/src/main/java/com/seugi/chatdatail/screen/ChatDetailInviteScreen.kt
- network/core/src/main/java/com/seugi/network/core/SeugiUrl.kt
- network/group-chat/src/main/java/com/seugi/network/groupchat/GroupChatDataSource.kt
- network/group-chat/src/main/java/com/seugi/network/groupchat/datasource/GroupChatDataSourceImpl.kt
- network/group-chat/src/main/java/com/seugi/network/groupchat/request/GroupChatMemberAddRequest.kt
- 채팅방 유저 초대 기능을 개발하였습니다.
- 채팅방에서 상대의 프로필을 누를 경우, 유저의 정보가 표시되도록 변경하였습니다.
- close #330
> Feature/Chat User Invite

- app/build.gradle.kts
- app/src/main/java/com/seugi/MainActivity.kt
- app/src/main/java/com/seugi/util/FirebaseMessageService.kt
- app/src/main/res/values/strings.xml
- designsystem/src/main/java/com/seugi/designsystem/component/Dialog.kt
- gradle/libs.versions.toml
> Feature/Create Firebase Cloud Message

- data/meal/src/main/java/com/seugi/data/meal/MealRepository.kt
- data/meal/src/main/java/com/seugi/data/meal/repository/MealRepositoryImpl.kt
- designsystem/src/main/java/com/seugi/designsystem/component/DatePicker.kt
- feature-main/home/src/main/java/com/seugi/home/HomeScreen.kt
- feature-main/home/src/main/java/com/seugi/home/card/MealCard.kt
- feature-main/home/src/main/java/com/seugi/home/navigation/HomeNavigation.kt
- feature-main/main/build.gradle.kts
- feature-main/main/src/main/java/com/seugi/main/MainScreen.kt
- feature-main/meal/build.gradle.kts
- feature-main/meal/src/main/java/com/seugi/meal/MealScreen.kt
- feature-main/meal/src/main/java/com/seugi/meal/MealViewModel.kt
- feature-main/meal/src/main/java/com/seugi/meal/model/MealUiState.kt
- feature-main/meal/src/main/java/com/seugi/meal/navigation/MealNavigation.kt
- local/room/src/main/java/com/seugi/local/room/dao/MealDao.kt
- network/core/src/main/java/com/seugi/network/core/SeugiUrl.kt
- network/meal/src/main/java/com/seugi/network/meal/MealDataSource.kt
- network/meal/src/main/java/com/seugi/network/meal/datasource/MealDataSourceImpl.kt
- settings.gradle.kts
- 급식 상세 화면을 만들었습니다.
- close #337
> Feature/Meal Screen

- data/message/src/main/java/com/seugi/data/message/mapper/MessageRoomEventMapper.kt
- data/message/src/main/java/com/seugi/data/message/model/MessageRoomEvent.kt
- feature-main/chat-datail/src/main/java/com/seugi/chatdatail/screen/ChatDetailChatScreen.kt
- data class model을 그대로 보내는 것을, 사람이 보기쉽게 String으로 변경하였습니다 .
- close #344
> Feature/Chat Deatil Ai Response Model to String

- data/message/src/main/java/com/seugi/data/message/MessageRepository.kt
- data/message/src/main/java/com/seugi/data/message/mapper/CatSeugiMapper.kt
- data/message/src/main/java/com/seugi/data/message/model/CatSeugiResponse.kt
- data/message/src/main/java/com/seugi/data/message/repository/MessageRepositoryImpl.kt
- feature-main/chat-seugi/src/main/java/com/seugi/chatseugi/ChatSeugiViewModel.kt
- feature-main/home/src/main/java/com/seugi/home/card/CatSeugiCard.kt
- network/message/src/main/java/com/seugi/network/message/MessageDataSource.kt
- network/message/src/main/java/com/seugi/network/message/datasource/MessageDataSourceImpl.kt
- network/message/src/main/java/com/seugi/network/message/request/CatSeugiRequest.kt
- network/message/src/main/java/com/seugi/network/message/response/CatSeugiResponse.kt
> Feature/Apply Ai Mapping

- feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailViewModel.kt
- feature-main/chat-datail/src/main/java/com/seugi/chatdatail/screen/ChatDetailChatScreen.kt
- AI의 메세지에 읽음 숫자가 줄어들지 않는 버그를 수정하였습니다.
- close #347
> Fix/Not Decrease Read Count

- feature-main/home/src/main/java/com/seugi/home/HomeScreen.kt
- feature-main/home/src/main/java/com/seugi/home/card/TaskCard.kt
- feature-main/task/src/main/java/com/seugi/task/TaskScreen.kt
- ??/?? 로 날짜를 표기하던 것을 기한 없음으로 표시하였습니다.
- 홈 화면에서 탑바가 스크롤에 포함되지 않게 하였습니다.
- close #349
> Feature/Edit Task Infinity Date Notation

- feature-main/profile/src/main/java/com/seugi/profile/ProfileScreen.kt
- 프로필 카드의 터치 영역을 늘렸습니다.
- close #355
> Feature/Profile Torch Area Bigger

- feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailScreen.kt
- feature-main/chat-datail/src/main/java/com/seugi/chatdatail/screen/ChatDetailChatScreen.kt
- network/core/src/main/java/com/seugi/network/core/di/NetworkModule.kt
- 메세지가 복사되도록 기능을 추가하였습니다.
- 채팅에서 소켓이 약 1~2분 유후상태일 경우 연결이 끊어지는 현상을 수정하였습니다.
- close #357
> Feature/Chat Detail Message Copy

- data/message/src/main/java/com/seugi/data/message/mapper/MessageRoomEventMapper.kt
- data/message/src/main/java/com/seugi/data/message/model/MessageRoomEvent.kt
- designsystem/src/main/java/com/seugi/designsystem/component/chat/ChatItem.kt
- feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailScreen.kt
- feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailViewModel.kt
- feature-main/chat-datail/src/main/java/com/seugi/chatdatail/screen/ChatDetailChatScreen.kt
- network/message/src/main/java/com/seugi/network/message/response/MessageRoomEventResponse.kt
- 채팅에서 날짜의 위치가 이상한 것을 수정하였습니다.
- 급식이 이전의 날일 경우 없습니다로 표기되는 문제를 해결하였습니다.
- 채팅방에서 나가거나, 들어올 경우 행위자만 표기 되고 초대받은 사람들이 표기되지 않는 문제를 해결하였습니다.
- close #351
> Fix/Chat Detail Issue

- common/src/main/java/com/seugi/common/utiles/Extension.kt
- data/message/src/main/java/com/seugi/data/message/mapper/MessageRoomEventMapper.kt
- data/message/src/main/java/com/seugi/data/message/model/MessageRoomEvent.kt
- designsystem/src/main/java/com/seugi/designsystem/component/chat/ChatItem.kt
- feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailViewModel.kt
- feature-main/chat-datail/src/main/java/com/seugi/chatdatail/screen/ChatDetailChatScreen.kt
- 채팅의 파일, 이미지 컴포넌트에서 읽음 개수와 timestamp를 추가하였습니다.
- close #364
> Feature/Add read count and timestamp in Img, File Component

- data/message/src/main/java/com/seugi/data/message/MessageRepository.kt
- data/message/src/main/java/com/seugi/data/message/mapper/MessageRoomEventMapper.kt
- data/message/src/main/java/com/seugi/data/message/model/MessageEmojiModel.kt
- data/message/src/main/java/com/seugi/data/message/model/MessageRoomEvent.kt
- data/message/src/main/java/com/seugi/data/message/repository/MessageRepositoryImpl.kt
- designsystem-preview/src/main/java/com/apeun/gidaechi/designsystem/preview/feature/ChatItem.kt
- designsystem/src/main/java/com/seugi/designsystem/component/Emoji.kt
- designsystem/src/main/java/com/seugi/designsystem/component/chat/ChatItem.kt
- feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailScreen.kt
- feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailViewModel.kt
- feature-main/chat-datail/src/main/java/com/seugi/chatdatail/screen/ChatDetailChatScreen.kt
- feature-main/chat-seugi/src/main/java/com/seugi/chatseugi/ChatSeugiScreen.kt
- network/core/src/main/java/com/seugi/network/core/SeugiUrl.kt
- network/message/src/main/java/com/seugi/network/message/MessageDataSource.kt
- network/message/src/main/java/com/seugi/network/message/datasource/MessageDataSourceImpl.kt
- network/message/src/main/java/com/seugi/network/message/request/EmojiRequest.kt
- network/message/src/main/java/com/seugi/network/message/response/MessageRoomEventResponse.kt
- network/message/src/main/java/com/seugi/network/message/response/message/MessageEmojiResponse.kt
- ui/src/main/java/com/seugi/ui/Utiles.kt
- 채팅방에서 이모지를 달 수 있는 기능을 추가하였습니다.
- close #368
> Feature/Chatting Emoji
